export const SHOW_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS ";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const FETCH_USER_TASKS_BEGIN = "FETCH_USER_TASKS_BEGIN";
export const FETCH_USER_TASKS_SUCCESS = "FETCH_USER_TASKS_SUCCESS";
export const FETCH_USER_TASKS_ERROR = "FETCH_USER_TASKS_ERROR";

export const CREATE_TASK_BEGIN = "CREATE_TASK_BEGIN";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const DELETE_TASK_BEGIN = "DELETE_TASK_BEGIN";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR"; 

export const UPDATE_TASK_BEGIN = "UPDATE_TASK_BEGIN ";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS ";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR "; 

export const REMOVE_USER = 'REMOVE_USER'